### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8081/build-server/test/test

###
POST http://localhost:8081/build-server/deployment/clone
Content-Type: application/json

{
  "url":"https://github.com/SUHEL3/testing-repo"
}

###
POST http://localhost:8081/build-server/deployment/build
Content-Type: application/json

{
  "folderPath": "repos/project1787480803367"
}